name: write to DB

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'name of the file to write to'
        required: true
        type: string
      data:
        description: 'data to write to the file'
        required: true
        type: object
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Print inputs
        run: |
          echo "String input: ${{ inputs.filename }}"
          echo "JSON input: ${{ inputs.data }}"
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
        
      - name: write data to file
        run: python write_data.py --file "${{ inputs.filename }}" --data "${{ inputs.data/\"/\\\" }}" # Replace with your script name

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add database/${{ inputs.filename }}
          git commit -m "Update data.json" -a || echo "No changes to commit"
          git push