name: write to DB

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'name of the file to write to'
        required: true
        type: string
      data:
        description: 'data to write to the file'
        required: true
        type: object
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print inputs
        run: |
          echo "String input: ${{ inputs.filename }}"
          echo "JSON input: ${{ inputs.data }}"